### ISSUE TITLE
Update readme file with more details

### ISSUE THREAD

**Issue by vibrantachintya** [twowaits/make-pull-request#28]
Add info about the kind of issues we have opened.

Some info about the process of raising PR and some best practices.

Also some info about Hacktoberfest for noobs to participate.

**Comment by navya252001** [comment]
I can help you
Sir please help me in HACKTOBER FEST 2020
We will honor all valid pull requests prior to this change, and as of October 3, 2020 at 12:00:00 UTC – and October 3 in all time zones – pull requests will only count toward earning a T-shirt or planting a tree if they are submitted in a repository classified with the ‘hacktoberfest’ topic. The pull requests will also need to be merged, approved by a maintainer, or labeled as ‘hacktoberfest-accepted’ in order to qualify. The deadline for completions, merging, labeling, and approving is November 1.
Latest guidelines issued by the organizers
I sincerely hope you will help me
https://hacktoberfest.digitalocean.com/hacktoberfest-update
I am attaching the link too for your convenience

**Comment by vibrantachintya** [comment]
Do mention college you belong to!

**Comment by navya252001** [comment]
Indian Institute of Technology(BHU) Varanasi

**Comment by vibrantachintya** [comment]
Good. We have some college specific communities, that's why asked!

**Comment by madhhuurrii** [comment]
Hii @vibrantachintya , I would like to update the readme with few basic steps for first time contributors on how to work locally with the code, with inages of fork, clone etc and git commands, and faq abt hacktoberfest 2020

**Comment by madhhuurrii** [comment]
Please assign me this issue, if possible!

**Comment by vibrantachintya** [comment]
Ok

**Comment by akhil27styles** [comment]
I  would like to update the readme @vibrantachintya
